# Generated by Django 5.1.6 on 2025-03-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergamestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGameStatus',
        ),
    ]
