# Generated by Django 5.1.6 on 2025-03-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_movie_adult_movie_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='users.actor'),
        ),
    ]
