# Generated by Django 5.1.6 on 2025-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_movie_custom_header_photo_movie_custom_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_main_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_recently_trending_big',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_recently_trending_small',
            field=models.BooleanField(default=False),
        ),
    ]
