# Generated by Django 5.1.6 on 2025-03-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_movie_is_main_movie_movie_is_recently_trending_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/genres_images', verbose_name='Изображение Жанра'),
        ),
    ]
