# Generated by Django 5.1.6 on 2025-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_genre_genre_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_color',
            field=models.CharField(max_length=10),
        ),
    ]
