# Generated by Django 5.1.6 on 2025-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_comment_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
