# Generated by Django 5.1.6 on 2025-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_movie_country_movie_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(choices=[('Director', 'Director'), ('Screenwriter', 'Screenwriter'), ('Producer', 'Producer')], max_length=50)),
            ],
        ),
    ]
