# Generated by Django 5.1.6 on 2025-04-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_crewmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(related_name='movies', to='users.crewmember'),
        ),
    ]
