# Generated by Django 5.1.6 on 2025-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_movie_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_photo',
            field=models.ImageField(blank=True, null=True, upload_to='genres_images', verbose_name='Изображение Жанра'),
        ),
    ]
