# Generated by Django 5.1.6 on 2025-04-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_movie_actors_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='similar_movies',
            field=models.ManyToManyField(related_name='similar_to', to='users.movie'),
        ),
    ]
