# Generated by Django 5.1.6 on 2025-04-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_movie_similar_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='similar_movies',
            field=models.ManyToManyField(to='users.movie'),
        ),
    ]
