# Generated by Django 5.1.6 on 2025-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_comment_game_alter_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_trailer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_trailer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
