# Generated by Django 5.1.6 on 2025-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_movie_video_movie_youtube_trailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('custom_photo', models.URLField(blank=True, null=True)),
                ('custom_header_photo', models.URLField(blank=True, null=True)),
                ('is_main_book', models.BooleanField(default=False)),
                ('rating_color', models.CharField(max_length=10)),
                ('btn_color', models.CharField(default='FF003C', max_length=10)),
            ],
        ),
    ]
