# Generated by Django 5.1.6 on 2025-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_url',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='btn_color',
        ),
        migrations.RemoveField(
            model_name='book',
            name='custom_header_photo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='custom_photo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_main_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating_color',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
