# Generated by Django 5.1.6 on 2025-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_cover_url_book_thumbnail_remove_book_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
