# Generated by Django 5.1.6 on 2025-04-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_book_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='btn_color',
            field=models.CharField(default='FF003C', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='custom_header_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='custom_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_main_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_recently_trending_big',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_recently_trending_small',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating_color',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
