# Generated by Django 5.1.6 on 2025-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_comment_btn_color_comment_custom_header_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='btn_color',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='custom_header_photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='custom_photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_main_movie',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_recently_trending_big',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_recently_trending_small',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating_color',
        ),
        migrations.AddField(
            model_name='book',
            name='btn_color',
            field=models.CharField(default='FF003C', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='custom_header_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='custom_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_main_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_recently_trending_small',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_color',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
