# Generated by Django 5.1.6 on 2025-04-21 00:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_comment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droppedgame',
            options={'verbose_name': 'Dropped Game', 'verbose_name_plural': 'Dropped Games'},
        ),
        migrations.AlterModelOptions(
            name='droppedmovie',
            options={'verbose_name': 'Dropped Movie', 'verbose_name_plural': 'Dropped Movies'},
        ),
        migrations.AlterModelOptions(
            name='favoritegame',
            options={'verbose_name': 'Favorite Game', 'verbose_name_plural': 'Favorite Games'},
        ),
        migrations.AlterModelOptions(
            name='favoritemovie',
            options={'verbose_name': 'Favorite Movie', 'verbose_name_plural': 'Favorite Movies'},
        ),
        migrations.AlterModelOptions(
            name='gamerating',
            options={'verbose_name': 'Game Rating', 'verbose_name_plural': 'Game Ratings'},
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={'verbose_name': 'Movie Rating', 'verbose_name_plural': 'Movie Ratings'},
        ),
        migrations.AlterModelOptions(
            name='playedgame',
            options={'verbose_name': 'Played Game', 'verbose_name_plural': 'Played Games'},
        ),
        migrations.AlterModelOptions(
            name='playinggame',
            options={'verbose_name': 'Playing Game', 'verbose_name_plural': 'Playing Games'},
        ),
        migrations.AlterModelOptions(
            name='watchedmovie',
            options={'verbose_name': 'Watched Movie', 'verbose_name_plural': 'Watched Movies'},
        ),
        migrations.AlterModelOptions(
            name='watchingmovie',
            options={'verbose_name': 'Watching Movie', 'verbose_name_plural': 'Watching Movies'},
        ),
        migrations.RemoveField(
            model_name='droppedgame',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='droppedmovie',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='favoritegame',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='watchedmovie',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='watchingmovie',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='book',
            name='custom_header_photo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='custom_photo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.book'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.game'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.movie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_color',
            field=models.CharField(default='white', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='similar_movies',
            field=models.ManyToManyField(blank=True, to='users.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='gamerating',
            unique_together={('user', 'game_id')},
        ),
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user', 'movie_id')},
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Book',
                'verbose_name_plural': 'Favorite Books',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
