# Generated by Django 5.1.6 on 2025-04-21 00:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_droppedgame_options_alter_droppedmovie_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropped_by', to='users.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dropped Book',
                'verbose_name_plural': 'Dropped Books',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='users.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Read Book',
                'verbose_name_plural': 'Read Books',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_by', to='users.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Book',
                'verbose_name_plural': 'Reading Books',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
