# Generated by Django 5.1.6 on 2025-05-03 01:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_droppedbook_quantity_droppedgame_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='users.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Rating',
                'verbose_name_plural': 'User Book Ratings',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserGameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='users.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game Rating',
                'verbose_name_plural': 'User Game Ratings',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='UserMovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='users.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Movie Rating',
                'verbose_name_plural': 'User Movie Ratings',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
