# Generated by Django 5.1.6 on 2025-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_userbookrating_usergamerating_usermovierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mgb_average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='mgb_rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='mgb_average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='mgb_rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='mgb_average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='mgb_rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
