# Generated by Django 5.1.6 on 2025-05-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_book_mgb_average_rating_book_mgb_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
