# Generated by Django 5.1.6 on 2025-05-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_game_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
