# Generated by Django 5.1.6 on 2025-06-01 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_game_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Контент (Фильм/Сериал)', 'verbose_name_plural': 'Контент (Фильмы/Сериалы)'},
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('tv', 'Сериал/Аниме')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='first_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_of_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='tv_shows', to='users.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(related_name='tv_shows_crew', to='users.crewmember'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tv_shows', to='users.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='similar_movies',
            field=models.ManyToManyField(blank=True, related_name='similar_tv_shows', to='users.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_custom',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/tv_shows', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
