# Generated by Django 5.1.6 on 2025-06-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_movie_options_movie_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
