# Generated by Django 5.1.6 on 2025-06-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_movie_youtube_trailer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
