# Generated by Django 5.1.6 on 2025-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_genre_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_color',
            field=models.CharField(blank=True, help_text="CSS-совместимая строка цвета для баннера профиля, например 'linear-gradient(...)' или '#RRGGBB'", max_length=100, null=True),
        ),
    ]
